import { StyleSheet } from "react-native";
import { colors } from "@/src/styles/Colors";

export const adminReportsStyles = StyleSheet.create({
  summaryCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 16,
  },
  summaryLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: "800",
  },
  summaryValue: {
    color: colors.text,
    fontSize: 28,
    fontWeight: "900",
    marginTop: 2,
  },
  refreshButton: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  loader: {
    marginTop: 44,
  },
  list: {
    gap: 12,
    marginTop: 14,
  },
  reportCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderLeftColor: colors.warning,
    borderLeftWidth: 5,
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  reportHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  reasonPill: {
    alignItems: "center",
    backgroundColor: colors.warningLight,
    borderRadius: 8,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  reasonText: {
    color: colors.warningText,
    fontSize: 12,
    fontWeight: "900",
  },
  reportDate: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
  },
  description: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
    marginTop: 12,
  },
  materialBox: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 12,
    padding: 12,
  },
  materialTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  materialMeta: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 4,
  },
  actions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 10,
  },
  secondaryButtonText: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: "800",
  },
  dangerButton: {
    alignItems: "center",
    backgroundColor: colors.error,
    borderRadius: 8,
    flexDirection: "row",
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 10,
  },
  dangerButtonText: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: "900",
  },
  disabledButton: {
    opacity: 0.55,
  },
  centered: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  centeredBlock: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 16,
    padding: 22,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "900",
    marginTop: 12,
    textAlign: "center",
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
    marginTop: 6,
    textAlign: "center",
  },
  retryButton: {
    marginTop: 12,
    padding: 8,
  },
  retryText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "900",
  },
});
