import { StyleSheet } from "react-native";

import { colors } from "@/src/styles/Colors";

export const filterModalStyles = StyleSheet.create({
  backdrop: {
    backgroundColor: "rgba(16, 24, 40, 0.42)",
    flex: 1,
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    flex: 1,
    maxHeight: "88%",
  },
  handle: {
    alignSelf: "center",
    backgroundColor: "#d1d5db",
    borderRadius: 3,
    height: 4,
    marginBottom: 6,
    marginTop: 10,
    width: 40,
  },
  header: {
    alignItems: "center",
    borderBottomColor: "#edf1f6",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 12,
    paddingHorizontal: 16,
  },
  title: {
    color: "#143a5f",
    fontSize: 18,
    fontWeight: "700",
  },
  scroll: {
    flex: 1,
    paddingHorizontal: 16,
  },
  sectionLabel: {
    color: "#5f584e",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
    marginBottom: 8,
    marginTop: 18,
    textTransform: "uppercase",
  },
  typeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  typeChip: {
    backgroundColor: "#f5f7fa",
    borderColor: "rgba(47, 111, 78, 0.16)",
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  typeChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  typeChipText: {
    color: "#403a32",
    fontSize: 13,
    fontWeight: "600",
  },
  typeChipTextActive: {
    color: "#ffffff",
  },
  subjectSearch: {
    alignItems: "center",
    backgroundColor: "#f5f7fa",
    borderColor: "#d1d5db",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  subjectSearchInput: {
    color: "#263747",
    flex: 1,
    fontSize: 14,
  },
  subjectList: {
    borderColor: "#edf1f6",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 8,
    maxHeight: 190,
    overflow: "hidden",
  },
  subjectItem: {
    alignItems: "center",
    borderBottomColor: "#edf1f6",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  subjectItemSelected: {
    backgroundColor: "#eef6ff",
  },
  subjectText: {
    color: "#263747",
    flex: 1,
    fontSize: 14,
    paddingRight: 8,
  },
  subjectTextSelected: {
    color: "#1f63b5",
    fontWeight: "700",
  },
  row: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  rowItem: {
    flex: 1,
  },
  textInput: {
    backgroundColor: "#f5f7fa",
    borderColor: "#d1d5db",
    borderRadius: 8,
    borderWidth: 1,
    color: "#263747",
    fontSize: 14,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  spacer: {
    height: 20,
  },
  footer: {
    borderTopColor: "#edf1f6",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 12,
    padding: 16,
  },
  clearButton: {
    alignItems: "center",
    borderColor: "#d1d5db",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
  },
  clearButtonText: {
    color: "#5f584e",
    fontSize: 15,
    fontWeight: "600",
  },
  applyButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 8,
    flex: 2,
    justifyContent: "center",
    minHeight: 48,
  },
  applyButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
});
