import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#eef4fb",
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    padding: 18,
    paddingBottom: 36,
  },
  headerTextWrap: {
	flex: 1,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 18,
    minHeight: 74,
  },
  brand: {
    color: "#c97913",
    fontSize: 16,
    fontWeight: "700",
  },
  title: {
    color: "#143a5f",
    fontSize: 27,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 32,
    maxWidth: 270,
  },
  headerIcon: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d7e5f5",
    borderRadius: 8,
    borderWidth: 1,
    height: 52,
    justifyContent: "center",
    width: 52,
  },
  navigationPanel: {
    backgroundColor: "#ffffff",
    borderColor: "#dfe7f0",
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginBottom: 14,
    padding: 12,
  },
  navButton: {
    alignItems: "center",
    backgroundColor: "#2f6f4e",
    borderRadius: 8,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    minHeight: 46,
    paddingHorizontal: 14,
  },
  navButtonSecondary: {
    backgroundColor: "rgba(47, 111, 78, 0.12)",
    borderColor: "rgba(47, 111, 78, 0.18)",
    borderWidth: 1,
  },
  navButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  navButtonTextDark: {
    color: "#214f37",
  },
  formSurface: {
    backgroundColor: "#ffffff",
    borderColor: "#dfe7f0",
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
  },
  field: {
    marginBottom: 16,
  },
  labelRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
    marginBottom: 7,
  },
  label: {
    color: "#425466",
    flexShrink: 0,
    fontSize: 14,
    fontWeight: "600",
  },
  fieldError: {
    color: "#d06d18",
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
  },
  input: {
    backgroundColor: "#f8fbfe",
    borderColor: "#cdd9e5",
    borderRadius: 8,
    borderWidth: 1,
    color: "#263747",
    fontSize: 15,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  textArea: {
    minHeight: 108,
  },
  row: {
    gap: 12,
  },
  rowItem: {
    flex: 1,
  },
  searchInputWrap: {
    position: "relative",
  },
  searchInput: {
    paddingRight: 42,
  },
  clearButton: {
    alignItems: "center",
    height: 40,
    justifyContent: "center",
    position: "absolute",
    right: 4,
    top: 4,
    width: 40,
  },
  suggestions: {
    backgroundColor: "#ffffff",
    borderColor: "#d7e1ec",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 6,
    overflow: "hidden",
  },
  suggestionItem: {
    borderBottomColor: "#edf1f6",
    borderBottomWidth: 1,
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  pressedSuggestion: {
    backgroundColor: "#eef6ff",
  },
  suggestionText: {
    color: "#263747",
    fontSize: 14,
  },
  selectButton: {
    alignItems: "center",
    backgroundColor: "#f8fbfe",
    borderColor: "#cdd9e5",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  selectButtonText: {
    color: "#263747",
    flex: 1,
    fontSize: 15,
  },
  uploadZone: {
    alignItems: "center",
    backgroundColor: "#f8fbfe",
    borderColor: "#b9cce1",
    borderRadius: 8,
    borderStyle: "dashed",
    borderWidth: 2,
    justifyContent: "center",
    minHeight: 138,
    padding: 18,
  },
  uploadZoneWithFiles: {
    minHeight: 96,
  },
  uploadText: {
    color: "#425466",
    fontSize: 15,
    fontWeight: "700",
    marginTop: 8,
    textAlign: "center",
  },
  uploadHint: {
    color: "#7a8797",
    fontSize: 12,
    marginTop: 4,
  },
  fileList: {
    gap: 8,
    marginTop: 10,
  },
  fileItem: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#dfe7f0",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 64,
    padding: 8,
  },
  fileOrder: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d8e2ec",
    borderRadius: 12,
    borderWidth: 1,
    height: 24,
    justifyContent: "center",
    marginRight: 8,
    width: 24,
  },
  fileOrderText: {
    color: "#425466",
    fontSize: 12,
    fontWeight: "700",
  },
  fileIcon: {
    alignItems: "center",
    backgroundColor: "#edf6ff",
    borderRadius: 8,
    height: 38,
    justifyContent: "center",
    marginRight: 8,
    width: 38,
  },
  fileTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  fileName: {
    color: "#263747",
    fontSize: 14,
    fontWeight: "600",
  },
  fileSize: {
    color: "#7a8797",
    fontSize: 12,
    marginTop: 2,
  },
  fileActions: {
    flexDirection: "row",
    gap: 4,
    marginLeft: 8,
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: "#f3f6fa",
    borderRadius: 8,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  iconButtonDanger: {
    backgroundColor: "#fff0f0",
  },
  iconButtonDisabled: {
    backgroundColor: "#f6f7f9",
  },
  commissionRow: {
    flexDirection: "row",
  },
  commissionPrefix: {
    alignItems: "center",
    backgroundColor: "#5d6d7d",
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
    justifyContent: "center",
    minHeight: 48,
    width: 58,
  },
  commissionPrefixText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  commissionInput: {
    borderBottomLeftRadius: 0,
    borderTopLeftRadius: 0,
    flex: 1,
  },
  submitButton: {
    alignItems: "center",
    backgroundColor: "#1f63b5",
    borderRadius: 8,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    minHeight: 52,
    paddingHorizontal: 18,
  },
  disabledButton: {
    opacity: 0.7,
  },
  submitButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  createdPanel: {
    backgroundColor: "#ecf7f0",
    borderColor: "#b7dfc4",
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 14,
    padding: 13,
  },
  createdHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  createdTitle: {
    color: "#247a48",
    fontSize: 15,
    fontWeight: "700",
  },
  createdText: {
    color: "#375647",
    fontSize: 13,
    marginTop: 6,
  },
  pressed: {
    opacity: 0.82,
  },
  pressedInput: {
    backgroundColor: "#eef6ff",
  },
  sheet: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    maxHeight: "78%",
    padding: 14,
    width: "100%",
  },
  sheetHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  sheetTitle: {
    color: "#143a5f",
    flex: 1,
    fontSize: 18,
    fontWeight: "700",
  },
  sheetScroll: {
    maxHeight: 430,
  },
  optionItem: {
    alignItems: "center",
    borderBottomColor: "#edf1f6",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 48,
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  optionItemSelected: {
    backgroundColor: "#eef6ff",
  },
  optionText: {
    color: "#263747",
    flex: 1,
    fontSize: 15,
    paddingRight: 10,
  },
  optionTextSelected: {
    color: "#1f63b5",
    fontWeight: "700",
  },
  emptySheetText: {
    color: "#667085",
    fontSize: 14,
    paddingVertical: 18,
    textAlign: "center",
  },
});


